project:
  type: website
  output-dir: docs

website:
  google-analytics: G-0YPBS9J7F2
  navbar:
    left:
      - href: index.qmd
        text: Angela Qian
      - href: strategic-marketing.qmd
        text: Projects
      - href: marketing-analytics.qmd
        text: Marketing Analytics
      - href: resume.qmd
        text: Resume
      - href: ga4-metrics.qmd
        text: GA4 Metrics
      - href: contact-me.qmd
        text: Contact

format:
  html:
    theme:
      - cosmo
      - theme.scss
    toc: true
    include-after-body: includes/project-modal.html
